<a href="https://colab.research.google.com/github/Yeshwanth2003/mlLab/blob/main/Assignment4GaussianNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install openml

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 41.8 MB/s eta 0:00:00
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11717 sha256=5a5a71f95a373b4e75ebc85b8b1f00c0fd8ebd9d831dfa13267d19d5ca71b541
  Stored in directory: /root/.cache/pip/wheels/00/23/31/5e562fce1f95aabe57f2a7320d07433ba1cd152bcde2f6a002
Successfully built liac-arff


In [3]:
import openml as op
import pandas as pd

data = op.datasets.get_dataset(40499)
df = pd.DataFrame(data.get_data()[0])

print(df['Class'].value_counts())
print("The class diveresity seems well balanced")

Class
1     500
2     500
3     500
4     500
5     500
6     500
7     500
8     500
9     500
10    500
11    500
Name: count, dtype: int64
The class diveresity seems well balanced


In [4]:
from sklearn.preprocessing import StandardScaler

sds = StandardScaler()
data = sds.fit_transform(df.drop('Class',axis=1))

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, df['Class'], test_size=0.2, random_state=42)

In [6]:
import numpy as np

class GaussianClassifier:
  def __init__(self):
    print("Gaussian Classifier")

  def fit(self,X,y):
    samples_c,features_c = X.shape
    self.classes_n_count = np.unique(y,return_counts=True)

    self.pre_mean = np.zeros((self.classes_n_count[0].shape[0],features_c))
    self.pre_var = np.zeros((self.classes_n_count[0].shape[0],features_c))
    self.pre_prob = np.zeros(self.classes_n_count[0].shape[0])
    tot = y.shape[0]

    for ind,cls in enumerate(self.classes_n_count[0]):
      X_cls = X[y==cls]
      self.pre_mean[ind,:] = X_cls.mean(axis=0)
      self.pre_var[ind,:] = X_cls.var(axis=0)
      self.pre_prob[ind] = self.classes_n_count[1][ind]/tot

  def predict(self,test):
    predictions = [self.__predict(x) for x in test]
    return predictions

  def __predict(self,x):
    vals = []

    for ind,cls in enumerate(self.classes_n_count[0]):
      var = self.pre_var[ind]
      mean = self.pre_mean[ind]
      n = np.exp((-(mean-x)**2)/(2*var))
      d = np.sqrt(2*3.14*var)
      n_by_d = np.sum(np.log(n/d))
      vals.append(n_by_d+np.log(self.pre_prob[ind]))
    # print(len(vals))
    return self.classes_n_count[0][np.argmax(vals)]

In [7]:
from sklearn.metrics import accuracy_score

model = GaussianClassifier()
model.fit(X_train,y_train)

predict = model.predict(X_test)
accuracy = accuracy_score(y_test,predict)
print(accuracy)

Gaussian Classifier
0.7818181818181819


In [11]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score

print(confusion_matrix(y_test,predict))
print(precision_score(y_test,predict,average='macro'))
print(recall_score(y_test,predict,average='macro'))

[[ 57   6   1   0   0   6   0   0   0  38   0]
 [ 15  42   1   0   0  25   0   0   0   6   0]
 [  2  11  54   0   0   3  20   8   2   0   0]
 [  0   0   0  90   0   0   3   0   0   0   0]
 [  1   0   0   0 105   0   0   0   0   0   0]
 [  2   7   1   0   1  79   0  10   0   2   0]
 [  0   1  19   0   0   5  83   2  10   0   0]
 [  0   0   1   0   0  13   8  72   0   0   0]
 [  0   0   1   0   0   0   6   0 101   0   0]
 [  0   0   2   0   0   0   0   0   0  87   0]
 [  0   0   1   0   0   0   0   0   0   0  90]]
0.78632977834707
0.7847140040761462


In [12]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train,y_train)

predict = model.predict(X_test)
accuracy = accuracy_score(y_test,predict)
print(accuracy)

0.7818181818181819


In [13]:
print(confusion_matrix(y_test,predict))
print(precision_score(y_test,predict,average='macro'))
print(recall_score(y_test,predict,average='macro'))

[[ 57   6   1   0   0   6   0   0   0  38   0]
 [ 15  42   1   0   0  25   0   0   0   6   0]
 [  2  11  54   0   0   3  20   8   2   0   0]
 [  0   0   0  90   0   0   3   0   0   0   0]
 [  1   0   0   0 105   0   0   0   0   0   0]
 [  2   7   1   0   1  79   0  10   0   2   0]
 [  0   1  19   0   0   5  83   2  10   0   0]
 [  0   0   1   0   0  13   8  72   0   0   0]
 [  0   0   1   0   0   0   6   0 101   0   0]
 [  0   0   2   0   0   0   0   0   0  87   0]
 [  0   0   1   0   0   0   0   0   0   0  90]]
0.78632977834707
0.7847140040761462
